export const BLOCKED_COUNTRIES = {
    AE: 'United Arab Emirates',
    AF: 'Afghanistan',
    BA: 'Bosnia and Herzegovina',
    CD: 'Democratic Republic of the Congo',
    CF: 'Central African Republic',
    CN: 'People’s Republic of China',
    CU: 'Cuba',
    DE: 'Germany',
    ER: 'Eritrea',
    ET: 'Ethiopia',
    GW: 'Guinea-Bissau',
    IR: 'Iran',
    IQ: 'Iraq',
    KP: 'Democratic People\'s Republic of Korea',
    LB: 'Lebanon',
    LY: 'Libya',
    RU: 'Russian Federation',
    SD: 'Sudan',
    SO: 'Somalia',
    SS: 'South Sudan',
    SY: 'Syria',
    UG: 'Uganda',
    US: 'United States of America',
    VU: 'Venezuela',
    YE: 'Yemen',
}
